### ISSUE TITLE
Installation ohne Composer

### ISSUE THREAD

**Issue by math-GH** [kozi/contao-metafields#1]
Hallo,

leider steht mir kein Composer zur Installation zur Verfügung. Nun versuche ich es händisch. Und bekomme die Erweiterung manuell nicht zum Laufen (Contao 3.5)

https://community.contao.org/de/showthread.php?65602-metafields-Installation-per-Hand

die Inhalte aus dem Ordner "contao" müssen in system/modules/metafields kopiert werden (checked). Im Backend danach die Datenbank (Erweiterungsverwaltung) aktualisieren. (checked). Im Backend ist in der linken Spalte unter "System" der neue Eintrag "Metadaten" zu finden.
Es scheint aber noch Probleme mit dem src-Ordner zu geben, da unter "Arikel" eine Fehlermeldung auftaucht

`Warning: in_array() expects parameter 2 to be array, null given in system\modules\core\library\Contao\System.php on line 160

#0 [internal function]: __error(2, 'in_array() expe...', 'D:\\Eigene Datei...', 160, Array)
#1 system\modules\core\library\Contao\System.php(160): in_array('getInstance', NULL)
#2 system\modules\core\library\Contao\Controller.php(491): Contao\System::importStatic('\\Metafields\\Met...')
#3 system\modules\core\dca\tl_content.php(1166): Contao\Controller::getContentElement(Object(Contao\ContentModel))
#4 system\modules\core\drivers\DC_Table.php(4284): tl_content->addCteType(Array)
#5 system\modules\core\drivers\DC_Table.php(378): Contao\DC_Table->parentView()
#6 system\modules\core\classes\Backend.php(650): Contao\DC_Table->showAll()
#7 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('article')
#8 contao\main.php(20): Contao\BackendMain->run()
#9 {main}

Fatal error: Class '\Metafields\MetafieldsHelper' not found in xxxxxx\system\modules\core\library\Contao\System.php on line 160`

Mir fehlt das Spezialwissen um die Compiser.json-Datei korrekt lesen zu können (speziell "autoload"-Einstellung).

Wer kann mir helfen, den src-Ordner korrekt zu kopieren?

**Comment by kozi** [comment]
Das Plugin funktioniert mit der aktuellen LTS-Version im Moment nicht korrekt. Werde den Fehler zeitnah beseitigen und dann auch ein kleines **HowTo zur manuellen Installation** hinzufügen.

**Comment by kozi** [comment]
In Version [1.3.2](https://github.com/kozi/contao-metafields/releases/tag/1.3.2) habe ich ein Archiv zur manuellen Installation hinzugefügt.
Werde das jetzt aber wahrscheinlich nicht für jede neue Version erstellen. Man muss allerdings nur den Ordner `src` in den Ordner `contao` verschieben und diesen dann in `metafields` umbenennen. Diesen Ordner kann man dann direkt in `system/modules` kopieren.

**Comment by math-GH** [comment]
ich habe das noch nicht ganz verstanden, wohin der src-Ordner kopiert werden soll. Welcher contao-Ordner ist gemeint?
Es gibt den contao-Ordner im Root. 
Es gibt den Ordner system\modules\core\library\Contao.

**Comment by kozi** [comment]
Das Archiv `metafields.zip` kann einfach wie gewohnt in `system/modules` entpackt werden. Danach ist die Erweiterung installiert bzw. dann fehlt nur noch das Datenbankupdate.

Der nachfolgende Absatz beschreibt nur wie ich die ZIP-Datei erstellt habe. Mit dem `contao`-Verzeichnis ist in diesem Fall das Verzeichnis in diesem Repository gemeint. 
> Werde das jetzt aber wahrscheinlich nicht für jede neue Version erstellen. Man muss allerdings nur den Ordner src in den Ordner contao verschieben und diesen dann in metafields umbenennen. Diesen Ordner kann man dann direkt in system/modules kopieren.

**Comment by math-GH** [comment]
Ich habe die metafields.zip geladen und entpackt:
![grafik](https://cloud.githubusercontent.com/assets/1645099/23329642/ba684cf2-fb3c-11e6-8004-2a380f507fc4.png)

Das Datenbank-Update habe ich ausgeführt.

Ein neues Attribut konnte ich problemlos anlegen:
![grafik](https://cloud.githubusercontent.com/assets/1645099/23329650/d95341d0-fb3c-11e6-882c-63b57aeaeacd.png)

In der Dateiverwaltung ist das neue Feld nicht zu finden und die "Standard-Contao-Metafields" fehlen:
![grafik](https://cloud.githubusercontent.com/assets/1645099/23329673/4413b81a-fb3d-11e6-8073-0d58ab0298ca.png)

Bearbeite ich einen Artikel, dann kommt weiterhin folgende Fehlermeldung:
`
Warning: in_array() expects parameter 2 to be array, null given in system\modules\core\library\Contao\System.php on line 160

#0 [internal function]: __error(2, 'in_array() expe...', 'D:\\Eigene Datei...', 160, Array)
#1 system\modules\core\library\Contao\System.php(160): in_array('getInstance', NULL)
#2 system\modules\core\library\Contao\Controller.php(491): Contao\System::importStatic('\\Metafields\\Met...')
#3 system\modules\core\dca\tl_content.php(1166): Contao\Controller::getContentElement(Object(Contao\ContentModel))
#4 system\modules\core\drivers\DC_Table.php(4284): tl_content->addCteType(Array)
#5 system\modules\core\drivers\DC_Table.php(378): Contao\DC_Table->parentView()
#6 system\modules\core\classes\Backend.php(650): Contao\DC_Table->showAll()
#7 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('article')
#8 contao\main.php(20): Contao\BackendMain->run()
#9 {main}


Fatal error: Class '\Metafields\MetafieldsHelper' not found in xxxx\system\modules\core\library\Contao\System.php on line 160`

**Comment by kozi** [comment]
Cache gelöscht?

**Comment by kozi** [comment]
Die autoload.php war im falschen Verzeichnis. https://github.com/kozi/contao-metafields/releases/tag/1.3.3

**Comment by math-GH** [comment]
super! Version 1.3.3 scheint zu laufen :)
